# Generated by Django 2.1.5 on 2019-02-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='nickname',
            field=models.CharField(default='Mae', max_length=50),
            preserve_default=False,
        ),
    ]
